<<<<<<< HEAD
INSERT INTO [PASSPORTTYPE] VALUES (0, '中国居民身份证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (1, '港澳通行证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (2, '台胞证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (3, '军官证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (4, '外国护照'); GO
=======
INSERT INTO [PASSPORTTYPE] VALUES (0, '中国居民身份证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (1, '港澳通行证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (2, '台胞证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (3, '军官证'); GO
INSERT INTO [PASSPORTTYPE] VALUES (4, '外国护照'); GO
>>>>>>> 40311c0... 更新源码2020-04-19
