INSERT INTO [ROOMSTATE] VALUES (0, '空房'); GO
INSERT INTO [ROOMSTATE] VALUES (1, '已住'); GO
INSERT INTO [ROOMSTATE] VALUES (2, '维修中'); GO
INSERT INTO [ROOMSTATE] VALUES (3, '脏房'); GO
INSERT INTO [ROOMSTATE] VALUES (4, '已预约'); GO
