<<<<<<< HEAD
INSERT INTO [ROOMTYPE] VALUES (0, '标准单人间'); GO
INSERT INTO [ROOMTYPE] VALUES (1, '标准双人间'); GO
INSERT INTO [ROOMTYPE] VALUES (2, '豪华单人间'); GO
INSERT INTO [ROOMTYPE] VALUES (3, '豪华双人间'); GO
INSERT INTO [ROOMTYPE] VALUES (4, '情侣套房'); GO
INSERT INTO [ROOMTYPE] VALUES (5, '总统套房'); GO
=======
INSERT INTO [ROOMTYPE] VALUES (0, '标准单人间'); GO
INSERT INTO [ROOMTYPE] VALUES (1, '标准双人间'); GO
INSERT INTO [ROOMTYPE] VALUES (2, '豪华单人间'); GO
INSERT INTO [ROOMTYPE] VALUES (3, '豪华双人间'); GO
INSERT INTO [ROOMTYPE] VALUES (4, '情侣套房'); GO
INSERT INTO [ROOMTYPE] VALUES (5, '总统套房'); GO
>>>>>>> 40311c0... 更新源码2020-04-19
