<<<<<<< HEAD
INSERT INTO [ROOMSTATE] VALUES (0, '空房'); GO
INSERT INTO [ROOMSTATE] VALUES (1, '已住'); GO
INSERT INTO [ROOMSTATE] VALUES (2, '维修中'); GO
INSERT INTO [ROOMSTATE] VALUES (3, '脏房'); GO
INSERT INTO [ROOMSTATE] VALUES (4, '已预约'); GO
=======
INSERT INTO [ROOMSTATE] VALUES (0, '空房'); GO
INSERT INTO [ROOMSTATE] VALUES (1, '已住'); GO
INSERT INTO [ROOMSTATE] VALUES (2, '维修中'); GO
INSERT INTO [ROOMSTATE] VALUES (3, '脏房'); GO
INSERT INTO [ROOMSTATE] VALUES (4, '已预约'); GO
>>>>>>> 40311c0... 更新源码2020-04-19
