<<<<<<< HEAD
INSERT INTO [SPENDTYPE] VALUES (0, '房费'); GO
INSERT INTO [SPENDTYPE] VALUES (1, '娱乐'); GO
INSERT INTO [SPENDTYPE] VALUES (2, '饮食'); GO
=======
INSERT INTO [SPENDTYPE] VALUES (0, '房费'); GO
INSERT INTO [SPENDTYPE] VALUES (1, '娱乐'); GO
INSERT INTO [SPENDTYPE] VALUES (2, '饮食'); GO
>>>>>>> 40311c0... 更新源码2020-04-19
