<<<<<<< HEAD
INSERT INTO [USERTYPE] VALUES (0, '普通用户'); GO
INSERT INTO [USERTYPE] VALUES (1, '钻石会员'); GO
INSERT INTO [USERTYPE] VALUES (2, '白金会员'); GO
INSERT INTO [USERTYPE] VALUES (3, '黄金会员'); GO
=======
INSERT INTO [USERTYPE] VALUES (0, '普通用户'); GO
INSERT INTO [USERTYPE] VALUES (1, '钻石会员'); GO
INSERT INTO [USERTYPE] VALUES (2, '白金会员'); GO
INSERT INTO [USERTYPE] VALUES (3, '黄金会员'); GO
>>>>>>> 40311c0... 更新源码2020-04-19
